# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Mitin
                                 A QGIS plugin
 this pugin saves all projects and closes qgis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-05-04
        copyright            : (C) 2025 by Mitin Artyom
        email                : .
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Mitin class from file Mitin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Mitin import Mitin
    return Mitin(iface)
