# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Yermakova
                                 A QGIS plugin
 вычисление NDWI на основе sentinel 2
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-04-14
        copyright            : (C) 2025 by Yermakova Melania
        email                : -
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Yermakova class from file Yermakova.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .yermakova import Yermakova
    return Yermakova(iface)
