# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Fanin
                                 A QGIS plugin
 Базовый плагин для расчета индекса NDVI 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-04-11
        copyright            : (C) 2025 by Fanin Egor
        email                : -
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Fanin class from file Fanin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .fanin import Fanin
    return Fanin(iface)
