# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Fanin
                                 A QGIS plugin
 Базовый плагин для расчета индекса NDVI 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-04-11
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Fanin Egor
        email                : -
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os
import glob
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QMessageBox
from qgis.core import QgsProject, QgsRasterLayer
from qgis.analysis import QgsRasterCalculatorEntry, QgsRasterCalculator


# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .fanin_dialog import FaninDialog
import os.path


class Fanin:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'Fanin_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Fanin')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('Fanin', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/fanin/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Fanin'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Fanin'),
                action)
            self.iface.removeToolBarIcon(action)

    def find_band(self, folder_path, band_number):
        """Поиск файла канала по номеру"""
        search_pattern = f"*_B{band_number}.TIF"
        files = glob.glob(os.path.join(folder_path, search_pattern))
        return files[0] if files else None

    def calculate_ndvi(self, folder_path):
        """Расчет NDVI из каналов в указанной директории"""
        try:
            red_band = self.find_band(folder_path, 4)
            nir_band = self.find_band(folder_path, 5)

            if not red_band or not nir_band:
                QMessageBox.critical(self.dlg, "Ошибка", 
                    "Не найдены необходимые каналы (B4 и B5)!")
                return False

            # Загрузка растров
            red_layer = QgsRasterLayer(red_band, "Red Band")
            nir_layer = QgsRasterLayer(nir_band, "NIR Band")

            if not red_layer.isValid() or not nir_layer.isValid():
                QMessageBox.critical(self.dlg, "Ошибка", 
                    "Ошибка загрузки растровых данных!")
                return False

            entries = []
    
            red_entry = QgsRasterCalculatorEntry()
            red_entry.ref = 'red@1'
            red_entry.raster = red_layer
            red_entry.bandNumber = 1
            entries.append(red_entry)
    
            nir_entry = QgsRasterCalculatorEntry()
            nir_entry.ref = 'nir@1'
            nir_entry.raster = nir_layer
            nir_entry.bandNumber = 1
            entries.append(nir_entry)

            formula = '(nir@1 - red@1) / (nir@1 + red@1)'
            output_path = os.path.join(folder_path, "NDVI.tif")

            # Расчет
            calc = QgsRasterCalculator(
                formula,
                output_path,
                'GTiff',
                red_layer.extent(),
                red_layer.width(),
                red_layer.height(),
                entries
            )
            
            result = calc.processCalculation()
            
            if result == 0:
                # Добавление результата в проект
                ndvi_layer = QgsRasterLayer(output_path, "NDVI")
                QgsProject.instance().addMapLayer(ndvi_layer)
                return True
            else:
                QMessageBox.critical(self.dlg, "Ошибка", 
                    "Ошибка при расчете NDVI!")
                return False

        except Exception as e:
            QMessageBox.critical(self.dlg, "Ошибка", 
                f"Произошла ошибка: {str(e)}")
            return False

    def run(self):
        """Основной метод работы плагина"""
        if self.first_start:
            self.first_start = False
            self.dlg = FaninDialog()

        self.dlg.show()
        
        if self.dlg.exec_():
            # Получаем путь из QgsFileWidget
            folder_path = self.dlg.file_widget.filePath()
            
            if not folder_path:
                QMessageBox.warning(self.dlg, "Предупреждение", 
                    "Директория не выбрана!")
                return
                
            if self.calculate_ndvi(folder_path):
                QMessageBox.information(self.dlg, "Успех", 
                    "NDVI успешно рассчитан и добавлен в проект!")