# -*- coding: utf-8 -*-
"""
/***************************************************************************
 VyugovDialog
                                 A QGIS plugin
 Export of images
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-04-19
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Vyugov Artyom
        email                : -
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtWidgets import QDialog, QSpinBox, QCheckBox, QLabel, QPushButton, QGridLayout
from qgis.gui import QgsFileWidget
from qgis.core import QgsMapSettings, QgsMapRendererParallelJob
from qgis.utils import iface

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'vyugov_dialog_base.ui'))

class VyugovDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(VyugovDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

    def setupUi(self, VyugovDialog):
        self.fileWidget = QgsFileWidget(self)
        self.fileWidget.setFilter("JPEG files (*.jpg *.jpeg)")
        
        self.qualitySpinBox = QSpinBox(self)
        self.qualitySpinBox.setRange(1, 100)
        self.qualitySpinBox.setValue(100)
        
        self.exportButton = QPushButton("Экспорт", self)
        
        self.gridLayout = QGridLayout(self)
        self.setLayout(self.gridLayout)

        self.gridLayout.addWidget(QLabel("Путь сохранения:"), 0, 0)
        self.gridLayout.addWidget(self.fileWidget, 0, 1)
        self.gridLayout.addWidget(QLabel("Качество JPG:"), 1, 0)
        self.gridLayout.addWidget(self.qualitySpinBox, 1, 1)
        self.gridLayout.addWidget(self.exportButton, 3, 0, 1, 2)
        
        self.exportButton.clicked.connect(self.accept)