# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Yermakova
                                 A QGIS plugin
 вычисление NDWI на основе sentinel 2
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-04-14
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Yermakova Melania
        email                : -
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
from qgis.core import QgsProject, QgsRasterLayer
from qgis.analysis import QgsRasterCalculatorEntry, QgsRasterCalculator 
from qgis import processing

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .yermakova_dialog import YermakovaDialog
import os.path
import os
import glob

class Yermakova:
    def __init__(self, iface):
        self.iface = iface
        self.actions = []
        self.first_start = True

    def initGui(self):
        action = QAction("NDWI", self.iface.mainWindow())
        action.triggered.connect(self.run)
        self.iface.addToolBarIcon(action)
        self.iface.addPluginToMenu("NDWI", action)
        self.actions.append(action)

    def unload(self):
        for action in self.actions:
            self.iface.removePluginMenu("NDWI", action)
            self.iface.removeToolBarIcon(action)

    def run(self):
        if self.first_start:
            self.first_start = False
            self.dlg = YermakovaDialog(self.iface.mainWindow())
    
        if self.dlg.exec_():
            folder = self.dlg.mQgsFileWidget.filePath()
        
            green_files = glob.glob(f"{folder}/*B3_60m.tif")
            nir_files = glob.glob(f"{folder}/*B8_60m.tif")
        
            if not green_files or not nir_files:
                self.iface.messageBar().pushMessage(
                    "Ошибка", 
                    "Файлы B3_60m.tif и/или B8_60m.tif не найдены", 
                    level=2, 
                    duration=3
                )
                return
        
            green_path = green_files[0]
            nir_path = nir_files[0]
        
            green_layer = QgsRasterLayer(green_path, "Green")
            nir_layer = QgsRasterLayer(nir_path, "NIR")
        
            entries = []
        
            green_entry = QgsRasterCalculatorEntry()
            green_entry.ref = 'green@1'
            green_entry.raster = green_layer
            green_entry.bandNumber = 1
            entries.append(green_entry)
        
            nir_entry = QgsRasterCalculatorEntry()
            nir_entry.ref = 'nir@1'
            nir_entry.raster = nir_layer
            nir_entry.bandNumber = 1
            entries.append(nir_entry)
        
            formula = '(green@1 - nir@1) / (green@1 + nir@1)'
            output_path = os.path.join(folder, "NDWI_60m.tif")
        
            calc = QgsRasterCalculator(
                formula,
                output_path,
                'GTiff',
                green_layer.extent(),
                green_layer.width(),
                green_layer.height(),
                entries
            )
        
            if calc.processCalculation() == 0:
                result_layer = QgsRasterLayer(output_path, "NDWI")
                QgsProject.instance().addMapLayer(result_layer)