# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Kotunova
                                 A QGIS plugin
 This plugin finds wood (nateral=woodd)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-04-19
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Kotunova Sofia
        email                : .
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
from qgis.core import QgsVectorLayer, QgsFeature, QgsProject, QgsFillSymbol
# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .Kotunova_dialog import KotunovaDialog
import os.path


class Kotunova:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'Kotunova_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Kotunova')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('Kotunova', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/Kotunova/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Kotunova'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Kotunova'),
                action)
            self.iface.removeToolBarIcon(action)

    def run(self):
        """Основной метод выполнения"""
        natural_layer = self.iface.activeLayer()

        if not natural_layer:
            self.iface.messageBar().pushCritical("Ошибка")
            return

        if not isinstance(natural_layer, QgsVectorLayer):
            self.iface.messageBar().pushCritical("Ошибка")
            return


        features = []
        valid_natural_values = ["wood"]

        for feature in natural_layer.getFeatures():
            if "natural" in feature.fields().names():
                natural_value = feature["natural"]
                if natural_value in valid_natural_values:
                    features.append(feature)

        if not features:
            self.iface.messageBar().pushWarning("Не найдено объектов с тегом natural=wood")
            return

        # Диагностика
        invalid_geoms = sum(1 for f in features if not f.geometry().isGeosValid())
        print(f"Найдено объектов: {len(features)}")
        print(f"Некорректных геометрий: {invalid_geoms}")
        print(f"CRS слоя: {natural_layer.crs().authid()}")

        # Создаем результирующий слой
        result_layer = QgsVectorLayer(
            f"Polygon?crs={natural_layer.crs().authid()}",
            "(natural=wood)",
            "memory"
        )

        # Настройка слоя
        result_layer.startEditing()
        result_layer.dataProvider().addAttributes(natural_layer.fields())
        result_layer.updateFields()

        # Копируем объекты с проверкой геометрии
        valid_features = []
        for feature in features:
            new_feature = QgsFeature()
            geom = feature.geometry()

            if not geom.isGeosValid():
                geom = geom.makeValid()

            new_feature.setGeometry(geom)
            new_feature.setAttributes(feature.attributes())
            valid_features.append(new_feature)

        result_layer.dataProvider().addFeatures(valid_features)
        result_layer.commitChanges()
        result_layer.updateExtents()

       
        symbol = QgsFillSymbol.createSimple({
            'color': '0,255,0,150',
            'color_border': '0,150,0',
            'width_border': '0.5'
        })
        result_layer.renderer().setSymbol(symbol)
        result_layer.triggerRepaint()


        QgsProject.instance().addMapLayer(result_layer)




        print("Слой успешно создан и добавлен на карту")
        self.iface.messageBar().pushSuccess("Готово", f"Найдено объектов: {len(features)}")
